from runtime.endpoints import worker_utilities as endpoints
from runtime import request_utils

def get_cassandra(auth, sql, c_type):
# Cassandra database select
#   auth: Authentication token generated by access.Authenticate()
#   sql: select sql target. Default value: select release_version from system.local
#   c_type: Default value: c OR r
    ep = endpoints.GET_CASSANDRA
    param_dict = {
        "sql": sql, 
        "type": c_type
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def get_cassandra_version(auth, params):
# Cassandra database version
#   auth: Authentication token generated by access.Authenticate()
#   params: (string)
    ep = endpoints.GET_CASSANDRA_VERSION
    param_dict = {
        "params": params
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def get_file(auth, file_name, lines):
# Obtain log file: Retrive number of lines from file.
#   auth: Authentication token generated by access.Authenticate()
#   file_name: file to read (str)
#   lines: number of lines to read (int)
    ep = endpoints.GET_FILE
    param_dict = {
        "file": file_name, 
        "lines": lines
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def get_ip(auth):
# Get IP of server.
#   auth: Authentication token generated by access.Authenticate()
    ep = endpoints.GET_IP
    resp = request_utils.create(auth, ep)
    meta = resp.json()
    return meta

def get_model_list(auth):
# List all models.
#   auth: Authentication token generated by access.Authenticate()
    ep = endpoints.GET_MODEL_LIST
    resp = request_utils.create(auth, ep)
    meta = resp.json()
    return meta

def get_properties_mojo_list(auth):
# Properties read for MOJO list
#   auth: Authentication token generated by access.Authenticate()
    ep = endpoints.GET_PROPERTIES_MOJO_LIST
    resp = request_utils.create(auth, ep)
    meta = resp.json()
    return meta

def get_properties_predict_param(auth):
# Properties read for predict parameter
#   auth: Authentication token generated by access.Authenticate()
    ep = endpoints.GET_PROPERTIES_PREDICT_PARAM
    resp = request_utils.create(auth, ep)
    meta = resp.json()
    return meta

def get_rest(auth, path):
# REST Interface: 
#    auth: Authentication token generated by access.Authenticate()
#    path: '-noData -u user -p pass http://lo...' 
#    use the -noData option to indicate the use of ecosystem API. 
#    Define user and password for authentication with -u and -p path='-key result -u user -p pass http://lo...' 
#    use the -key [keyvalue] option to indicate the use of API where document is in JSON key.
    ep = endpoints.GET_REST
    param_dict = {
        "path": path
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def list_to_matrix(auth, params):
# Create matrix from transcation list from properties file as setup in budget tracker.
#   auth: Authentication token generated by access.Authenticate()
#   params: {type:'csv'} or {type:'json'}
    ep = endpoints.LIST_TO_MATRIX
    param_dict = {
        "params": params
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def matrix_to_list(auth, params):
# Create list from matrix, import csv file.
#   auth: Authentication token generated by access.Authenticate()
#   params: {test: true, file:'./file.csv'} (use test setting to check before update)
    ep = endpoints.MATRIX_TO_LIST
    param_dict = {
        "params": params
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def pull_kafka_topic(auth, message, params):
# Pull message from Kafka topic
#   auth: Authentication token generated by access.Authenticate()
#   message: Default value : [{}]
#   params: Default value : [{"TOPIC_NAME":"ecosystem1","log":"true"}]
    ep = endpoints.PULL_KAFKA_TOPIC
    param_dict = {
        "message": message, 
        "params": params
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def push_kafka_topic(auth, message, params):
# Push predictor scored result onto Kafka
#   auth: Authentication token generated by access.Authenticate()
#   message: Default value : [{"id1":"message1"},{"id2":"message2"}]
#   params: Default value : [{"TOPIC_NAME":"ecosystem1","log":"true"}]
    ep = endpoints.PUSH_KAFKA_TOPIC
    param_dict = {
        "message": message, 
        "params": params
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def update_mojo_list(auth, params):
# Update properties: MOJO list.
#   auth: Authentication token generated by access.Authenticate()
#   params: (str)
    ep = endpoints.UPDATE_MOJO_LIST
    param_dict = {
        "params": params
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def update_predict_param(auth, params):
# Update properties: Predict param
#   auth: Authentication token generated by access.Authenticate()
#   params: (str)
    ep = endpoints.UPDATE_PREDICT_PARAM
    param_dict = {
        "params": params
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def upload_file(auth, path, target_path):
    ep = endpoints.UPLOAD_FILE
    fileFp = open(path, "rb")
    files = {"file": fileFp}
    data = {"path": target_path}
    resp = request_utils.create_only_auth(auth, ep, data=data, files=files)
    return resp

def file_database_import(auth, database, collection, file_name):
    ep = endpoints.FILE_DATABASE_IMPORT
    param_dict = {
        "database": database,
        "collection": collection,
        "file": file_name
    }
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

def get_property(auth, property_key):
	ep = endpoints.GET_PROPERTY
	param_dict = {
		"key": property_key
	}
	resp = request_utils.create_only_auth(auth, ep, params=param_dict)
	data = resp.content.decode("utf-8")
	return data

def update_properties(auth, properties):
    ep = endpoints.UPDATE_PROPERTIES
    resp = request_utils.create_only_auth(auth, ep, data=properties)
    return resp

def refresh(auth):
    ep = endpoints.REFRESH
    resp = request_utils.create(auth, ep)
    meta = resp.content
    return meta

def get_spend_personality(auth, campaign, channel, customer, params, subcampaign, userid):
    ep = endpoints.GET_SPEND_PERSONALITY
    param_dict = {
    	"campaign": campaign,
      "channel": channel, 
      "customer":customer, 
      "params":params, 
      "subcampaign":subcampaign, 
      "userid":userid}
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta


def get_financial_wellness(auth, campaign, channel, customer, params, subcampaign, userid):
    ep = endpoints.GET_FINANCIAL_WELLNESS
    param_dict = {"campaign": campaign,
                  "channel": channel, 
                  "customer":customer, 
                  "params":params, 
                  "subcampaign":subcampaign, 
                  "userid":userid}
    resp = request_utils.create(auth, ep, params=param_dict)
    meta = resp.json()
    return meta

